### Verbo GET – listar todos
GET http://localhost:8000/funcionario/ HTTP/1.1


### Verbo POST – adicionar
POST http://127.0.0.1:8000/funcionario/ HTTP/1.1 #inserir
content-type: application/json

{
    "nome" : "hh",
    "cpf" : "hh",
    "telefone" : "hh",
    "senha" : "hh",
    "matricula" : "hh",
    "grupo" : 2
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/funcionario/6 HTTP/1.1 #Editar 
content-type: application/json

{
    "nome" : "Bolinhas Testes",
    "cpf" : "01923g756",
    "telefone" : "49f98989",
    "senha" : "abc",
    "matricula" : "54121",
    "grupo" : 2
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/funcionario/6 HTTP/1.1