### Verbo GET – listar todos
GET http://localhost:8000/pr/ HTTP/1.1

### Verbo GET – listar um
GET http://localhost:8000/cliente/10 HTTP/1.1

### Verbo POST – adicionar
POST http://127.0.0.1:8000/cliente/ HTTP/1.1
content-type: application/json

{
    "nome" : "Cliente da silva",
    "cpf" : "01923874656",
    "telefone" : "49988234567",
    "senha" : "bolinhas",
    "comprar_fiado" : false,
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/cliente/2 HTTP/1.1
content-type: application/json

{
    "id_cliente": 1,
    "nome" : "Cliente dos Testes",
    "cpf" : "12345678909",
    "telefone" : "49898989",
    "senha" : "abc",
    "comprar_fiado" : true,
    "dia_fiado" : 2
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/cliente/3 HTTP/1.1