### Verbo GET – listar todos
GET http://localhost:8000/produto/1 HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey

# GET http://localhost:8000/produto/1 HTTP/1.1
# x-token: abcBolinhasToken
# x-key: abcBolinhasKey

### Verbo POST – adicionar
POST http://127.0.0.1:8000/produto/ HTTP/1.1
content-type: application/json
x-token: abcBolinhasToken
x-key: abcBolinhasKey

{
    "nome" : "guarana",
    "descricao" : "600ml",
    "valor_unitario" : 6
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/produto/2 HTTP/1.1
content-type: application/json
x-token: abcBolinhasToken
x-key: abcBolinhasKey

{
    "id": 1,
    "nome" : "kuat",
    "descricao" : "600ml",
    "valor_unitario" : 5
}

### Verbo DELETE - excluir

DELETE http://127.0.0.1:8000/produto/16 HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey

